### ISSUE TITLE
Check and compare objects value with check_result

### ISSUE THREAD

**Issue by despatates** [lumapps/lumRest#14]
With `check_result` option, we can check primitive values and list values. It would be great to compare objects.
Example:

``` yaml
- my.endpoint:
  save_result: myObject
  check_result: myObject == myOtherObject
```

And more :

``` yaml
- my.endpoint:
  save_result: myObject
  check_result:
    - myObject.attribute: myOtherObject.attribute
    - myObject.id: myOtherObject.id
    - myObject.attr: "#r#[a-z]+"
```

Thanks LumRest team :smile:

**Comment by despatates** [comment]
Second example is already possible:
```yaml
- my.endpoint:
  save_result: myObject
  check_result: {
    attribute: !expr myOtherObject.attribute, 
    id: !expr myOtherObject.id,
    attr: "#r#[a-z]+"
  }
```
