### ISSUE TITLE
#MATCH# check is not checking all attributes

### ISSUE THREAD

**Issue by despatates** [lumapps/lumRest#19]
When two attributes must be checked in a `#MATCH#` case, only one is checked (seems to be the first in alphabetical order).

Example:
This test is valid.
```yaml
  - content.revision.list:
      contentId: !expr content.id
    description: List revisions for the content (0:DRAFT).
    check_code: 200
    check_result: {
      items: ["#MATCH#",
        {version: 0, status: "DRAFT"},
      ]
    }
```

If I change the value of `status` in the `check_result`, the test fail (as wanted).
```yaml
  - content.revision.list:
      contentId: !expr content.id
    description: List revisions for the content (0:DRAFT).
    check_code: 200
    check_result: {
      items: ["#MATCH#",
        {version: 0, status: "-NOT-WANTED-VALUE-"},
      ]
    }
```

But if I do the same on `version` attribute, the test is valid, and must not !
```yaml
  - content.revision.list:
      contentId: !expr content.id
    description: List revisions for the content (0:DRAFT).
    check_code: 200
    check_result: {
      items: ["#MATCH#",
        {version: "-NOT-WANTED-VALUE-", status: "DRAFT"},
      ]
    }
```
