### ISSUE TITLE
Update auth parameters for one test case update global auth configuration

### ISSUE THREAD

**Issue by despatates** [lumapps/lumRest#5]
When using a global auth.yaml file, editing auth parameters for one test case is editing global config.

Example :
`auth.yaml`

``` yaml
auth:
  email: "admin@managemybudget.net"
  client_secret: "../app/server/api/privatekey.pem"
  client_id: "XXXXXXXX@developer.gserviceaccount.com"
  oauth_scope:
      - "https://www.googleapis.com/auth/userinfo.email"

```

`content_list.yaml`

``` yaml
- content.list:
    lang: 'fr'
    instance: "1234
  config:
    auth:
      email: "test@managemybudget.net"
  check_result: 200
```

The next test case will be executed with `test@managemybudget.net` if no `config/auth/email` is set. It should be executed with `admin@managemybudget.net`.
